### ISSUE TITLE
PHP 8: Not able to export custom flexible layout

### ISSUE THREAD

**Issue by djzwerg** [backdrop-contrib/flexible_layout#8]
When I'm going to export my layout the following error occurs:
`natsort(): Argument #1 ($array) must be of type array, null given`

Backdrop core version: 1.23.0
Database version: MySQL 8.0.30
PHP version: 8.0.25

Steps to reproduce:

1. install flexible_layout module
2. install flexivle_template
3. create own layout, e.g. 'test'
4. save layout
5. try to export on admin/structure/layouts/settings

**Comment by djzwerg** [comment]
Backdrop error logs:

`TypeError: natsort(): Argument #1 ($array) must be of type array, null given in natsort() (line 313 of /mypath/core/modules/config/config.admin.inc).`

`Warning: Undefined array key "Flexible layout templates" in config_export_single_form() (line 312 of /mypath/core/modules/config/config.admin.inc).`

`Warning: Trying to access array offset on value of type null in field_config_label_instance() (line 436 of /mypath/core/modules/field/field.module).` (3 times)

**Comment by djzwerg** [comment]
For now I think this is an issue with the PHP version. Using PHP 7.4 the export feature works.

**Comment by docwilmot** [comment]
To be honest, this module wont be maintained since this functionality is in core now. Was there a particular reason you wanted this instead of core flexible layouts?

**Comment by djzwerg** [comment]
I didn't know that this feature has been moved to core. It's one of my standard Backdrop modules during installation process.

**Comment by djzwerg** [comment]
Maybe this issue belongs to the flexible template module instead of flexible layout? The error occurs on exporting the template not the layout. The URL path is a bit confusing.
